### ISSUE TITLE
database structure

### ISSUE THREAD

**Issue by m4s0** [fastnloud/jaapsblog#1]
Hi Jaap, I would like to run this project but there is no database, I need database structure to run it.

Thanks
Marco

**Comment by fastnloud** [comment]
Hello Mark,

I've added an EER-diagram:
https://github.com/fastnloud/jaapsblog/blob/master/docs/mysqlworkbench/dbmodel.mwb

Let me know if that works for you.

For the site to work you have to add 2 pages home (url_string = home, route = page) and blog (url_string = blog, route = blog).

If you have any further questions let me know.

Jaap

**Comment by m4s0** [comment]
Thanks.
Auth module seems to be not complete, there is no way to access other resources.

Marco

**Comment by fastnloud** [comment]
Go to '/admin': I use ExtJS 4.2.1 as basic CMS, which will post JSON data. The Auth module is there to validate these requests.

I.e. to add pages/blog posts you are required to be logged on.

Regards,
Jaap

**Comment by zaherkassem** [comment]
Hi,

i don't know how to open the "dbmodel.mwb" file, please attach sql format.

thanks.

**Comment by fastnloud** [comment]
http://dev.mysql.com/downloads/workbench/
